# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0002_auto_20160512_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='tollcounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_no', models.CharField(max_length=80)),
                ('counter_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='toll',
        ),
    ]
