# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0003_auto_20160512_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_no', models.CharField(max_length=80)),
                ('Registration_no', models.CharField(max_length=50)),
                ('Date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
