# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0004_tolltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payments', models.CharField(max_length=80)),
                ('Receive', models.CharField(max_length=50)),
                ('Date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Balance', models.CharField(max_length=80)),
            ],
        ),
    ]
