# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0006_auto_20160515_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Registration_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_rate',
            field=models.CharField(max_length=50),
        ),
    ]
