# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0007_auto_20160515_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollcounter',
            name='id',
        ),
        migrations.AlterField(
            model_name='tollcounter',
            name='counter_no',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.tollcounter'),
        ),
    ]
