# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0009_auto_20160515_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_no',
            field=models.ForeignKey(db_column='tollcounter_id', on_delete=django.db.models.deletion.CASCADE, to='toll.tollcounter'),
        ),
    ]
