# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0011_auto_20160515_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_no',
            field=models.CharField(default='Counter 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_rate',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.DeleteModel(
            name='tollcounter',
        ),
    ]
