# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0012_auto_20160515_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='tollcounter',
            fields=[
                ('counter_no', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('counter_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.tollcounter'),
        ),
        migrations.AlterField(
            model_name='tolltransaction',
            name='counter_rate',
            field=models.CharField(max_length=50),
        ),
    ]
