# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0013_auto_20160515_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolltransaction',
            old_name='counter_no',
            new_name='counterno',
        ),
    ]
